/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
static yyconst short int yy_acclist[233] =
    {   0,
       56,   54,   55,   18,   54,   55,    1,   55,    2,   18,
       54,   55,   24,   54,   55,   14,   54,   55,   54,   55,
       28,   54,   55,   31,   54,   55,   54,   55,   48,   54,
       55,   49,   54,   55,   26,   54,   55,   20,   54,   55,
       52,   54,   55,   21,   54,   55,   27,   54,   55,   44,
       54,   55,   53,   54,   55,   37,   54,   55,   35,   54,
       55,   36,   54,   55,   43,   54,   55,   46,   54,   55,
       47,   54,   55,   32,   54,   55,   43,   54,   55,   43,
       54,   55,   43,   54,   55,   43,   54,   55,   43,   54,
       55,   43,   54,   55,   43,   54,   55,   43,   54,   55,

       43,   54,   55,   43,   54,   55,   43,   54,   55,   43,
       54,   55,   43,   54,   55,   50,   54,   55,   33,   54,
       55,   51,   54,   55,   25,   54,   55,   10,   55,   12,
       55,    9,   55,   11,   55,   18,   41,   14,   13,   22,
       44,   23,    6,    5,   45,   30,   39,   40,   38,   29,
       42,   43,   43,   43,   43,   43,   43,   43,   43, 8209,
       43,16401,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   34,   10,    9,    8,    7,   15,   15,    5,
       45,   43,   43,   43,   43,   43,   43, 8209, 8209,   42,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   16,

       15,   16,   43,   43,   43,   43, 8209,   43,16401,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,    4,    4,    4,   19,    3,
       19,    3
    } ;

static yyconst short int yy_accept[186] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   13,
       16,   19,   21,   24,   27,   29,   32,   35,   38,   41,
       44,   47,   50,   53,   56,   59,   62,   65,   68,   71,
       74,   77,   80,   83,   86,   89,   92,   95,   98,  101,
      104,  107,  110,  113,  116,  119,  122,  125,  128,  130,
      132,  134,  136,  137,  138,  139,  140,  140,  140,  140,
      140,  140,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  150,  151,  151,  152,  153,  154,  155,  156,  157,
      158,  159,  160,  163,  164,  165,  166,  167,  168,  169,
      170,  171,  172,  173,  174,  175,  176,  177,  178,  178,

      178,  178,  179,  179,  179,  179,  180,  181,  182,  183,
      184,  185,  186,  187,  188,  189,  191,  192,  193,  194,
      195,  196,  197,  198,  199,  200,  200,  200,  201,  201,
      201,  203,  204,  205,  206,  207,  210,  211,  212,  213,
      214,  215,  216,  216,  216,  217,  218,  219,  220,  221,
      222,  222,  222,  223,  224,  224,  224,  225,  226,  226,
      226,  226,  226,  226,  226,  227,  228,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  230,  232,  233,  233
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   25,   40,   41,   42,   43,
       44,   25,   25,   45,   46,   47,   48,   49,   50,   25,
       25,   25,   51,   52,   53,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    1,    5,    1,    1,    1,    6,    5,    7,    7,
        1,    1,    1,    1,    8,    1,    1,    1,    1,    9,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[201] =
    {   0,
        0,    0,   52,   53,  432,  585,   55,  585,   56,  408,
      424,   28,  585,  585,   51,  585,  585,  585,   49,  585,
       56,   61,   63,  585,   62,  406,   63,   77,  585,  585,
      585,   85,   87,   88,   86,   96,   90,   91,  105,   99,
      100,  101,  102,  104,  585,  376,  585,  585,    0,  585,
      101,  414,  116,  585,  367,  585,  333,  322,  353,  352,
      145,  585,  104,  585,  585,    0,  109,  585,  585,  585,
      585,  585,  139,  585,  141,  145,  154,  150,  149,  155,
      158,  159,  163,  164,  167,  175,  178,  180,  192,  194,
      195,  196,  204,  585,    0,  104,  585,  585,  325,  327,

      347,  585,  346,  324,  321,  305,    0,  193,  205,  215,
      216,  217,  219,  227,  229,  585,  233,  241,  242,  244,
      253,  255,  258,  257,  261,  274,  270,  585,  299,  285,
      585,  267,  269,  263,  271,  272,  275,  277,  281,  289,
      290,  294,  244,  229,  295,  306,  308,  310,  319,  321,
      221,  217,  322,  324,  243,  207,  332,  335,  230,  336,
      370,  228,  218,  214,  421,  213,    0,    0,  191,   60,
      328,  170,  145,  135,  140,  333,  103,  331,  420,   69,
      585,  585,  585,  585,  471,  480,  489,  496,  505,  514,
      523,  532,  541,  550,  557,  564,  570,   65,  573,  576

    } ;

static yyconst short int yy_def[201] =
    {   0,
      184,    1,  185,  185,  184,  184,  184,  184,  184,  184,
      186,  184,  184,  184,  187,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  188,  184,  184,
      184,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  184,  184,  184,  184,  189,  184,
      184,  184,  184,  184,  186,  184,  184,  184,  190,  184,
      191,  184,  184,  184,  184,  192,  184,  184,  184,  184,
      184,  184,  184,  184,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  184,  189,  184,  184,  184,  184,  184,

      190,  184,  193,  194,  190,  184,  192,  184,  188,  188,
      188,  188,  188,  188,  184,  184,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  184,  184,  184,  193,  194,
      184,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  184,  184,  188,  188,  188,  188,  188,  188,
      184,  184,  188,  188,  184,  184,  188,  188,  195,  184,
      184,  184,  196,  197,  161,  165,  161,  198,  196,  196,
      199,  200,  184,  184,  200,  199,  184,  184,  184,  184,
      184,  184,  184,    0,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184

    } ;

static yyconst short int yy_nxt[640] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,    6,   22,   23,   23,
       24,   25,   26,   27,   28,   29,    6,   30,   31,   28,
       28,   32,   33,   34,   35,   36,   28,   28,   37,   28,
       38,   39,   28,   28,   40,   41,   28,   42,   43,   44,
       45,   46,   47,   48,   50,   50,   53,   53,   53,   53,
       60,   57,   62,  184,   51,   51,   58,   63,   63,   52,
       52,   64,  172,   65,   63,   63,  173,   61,   66,   67,
       73,   63,   63,   68,   69,   71,   72,   74,   73,   73,
       73,   73,  183,   73,   73,   74,   74,   74,   74,   73,

       74,   74,   73,   73,   73,   73,   74,   73,   73,   74,
       74,   74,   74,   96,   74,   74,   96,   53,   97,   53,
       67,   97,   63,   63,   77,   83,   80,  108,  108,   76,
       78,   79,   84,   87,   85,   86,   81,   88,   89,   82,
      180,   93,   73,   91,   73,   92,   90,  104,   73,   74,
      105,   74,   73,   73,  106,   74,  177,   73,   73,   74,
       74,   73,   73,  105,   74,   74,  115,   73,   74,   74,
       73,  105,  179,  116,   74,  105,  105,   74,   73,  109,
      105,   73,  178,   73,  110,   74,  177,  105,   74,  105,
       74,  105,  111,  105,  169,   73,  112,   73,   73,   73,

      113,  114,   74,   83,   74,   74,   74,   73,   73,  117,
       83,  108,  108,  118,   74,   74,  166,  169,   73,   73,
       73,  169,   73,  120,  119,   74,   74,   74,  121,   74,
       73,  162,  115,  159,  124,  132,   73,   74,  122,  116,
      123,  160,  125,   74,   73,   73,  159,   73,  134,  168,
      156,   74,   74,   83,   74,  155,   73,  135,   73,   83,
       73,   73,  133,   74,   73,   74,   73,   74,   74,   83,
       73,   74,   73,   74,   73,  115,  152,   74,   73,   74,
       73,   74,  116,  136,   73,   74,  151,   74,  138,  137,
       83,   74,   73,   73,  128,  139,  141,   73,   73,   74,

       74,  142,  140,  146,   74,   74,   83,  145,  128,   73,
      144,   73,  143,   73,  102,  148,   74,   83,   74,  147,
       74,  149,   73,   83,   73,   73,  150,   73,   83,   74,
      131,   74,   74,  128,   74,   73,  181,  153,   73,  162,
       83,  163,   74,   83,  174,   74,  175,  175,  181,  174,
       83,  175,  175,  163,  181,  128,  128,  164,  158,  127,
      126,  102,  102,  154,  100,   83,   83,   99,   83,  157,
      165,  165,   56,  166,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  167,  167,
      165,  165,  165,  165,  167,  165,  165,  165,  165,  165,

      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      165,  165,  165,  165,  165,  181,   98,   94,   70,   56,
       54,  184,  184,  184,  184,  184,  184,  181,  184,  165,
      165,  184,  184,  182,  184,  165,  184,  184,  184,  184,
      184,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       55,  184,   55,   55,   55,   55,   55,   55,   55,   59,
      184,   59,   59,   59,   59,   59,   59,   59,   75,   75,

      184,  184,   75,   75,   75,   95,  184,   95,   95,  184,
       95,   95,   95,   95,  101,  184,  101,  101,  101,  101,
      101,  101,  101,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  107,  184,  107,  107,  107,  107,  107,  107,
      107,  129,  184,  129,  129,  129,  129,  129,  129,  129,
      130,  184,  130,  130,  130,  130,  130,  130,  130,  161,
      184,  184,  184,  184,  161,  161,  170,  184,  184,  184,
      184,  170,  171,  184,  184,  184,  184,  171,  176,  176,
      176,  175,  175,  175,    5,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184
    } ;

static yyconst short int yy_chk[640] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    7,    9,    7,    9,
       15,   12,   19,  170,    3,    4,   12,   19,   19,    3,
        4,   21,  198,   22,   21,   21,  170,   15,   22,   23,
       28,   23,   23,   25,   25,   27,   27,   28,   32,   35,
       33,   34,  180,   37,   38,   32,   35,   33,   34,   36,

       37,   38,   40,   41,   42,   43,   36,   44,   39,   40,
       41,   42,   43,   51,   44,   39,   96,   53,   51,   53,
       63,   96,   63,   63,   33,   37,   35,   67,   67,   32,
       33,   34,   37,   40,   38,   39,   36,   41,   41,   36,
      177,   44,   73,   42,   75,   43,   41,   61,   76,   73,
       61,   75,   79,   78,   61,   76,  175,   77,   80,   79,
       78,   81,   82,   61,   77,   80,   83,   84,   81,   82,
       85,   61,  174,   83,   84,   61,   61,   85,   86,   76,
       61,   87,  173,   88,   77,   86,  172,   61,   87,   61,
       88,   61,   78,   61,  169,   89,   79,   90,   91,   92,

       80,   81,   89,   82,   90,   91,   92,   93,  109,   85,
       84,  108,  108,   86,   93,  109,  166,  164,  110,  111,
      112,  163,  113,   88,   87,  110,  111,  112,   89,  113,
      114,  162,  115,  159,   92,  109,  117,  114,   90,  115,
       91,  156,   93,  117,  118,  119,  155,  120,  112,  162,
      152,  118,  119,  113,  120,  151,  121,  114,  122,  110,
      124,  123,  111,  121,  125,  122,  134,  124,  123,  117,
      132,  125,  133,  134,  135,  136,  144,  132,  137,  133,
      138,  135,  136,  118,  139,  137,  143,  138,  120,  119,
      124,  139,  140,  141,  130,  121,  123,  142,  145,  140,

      141,  125,  122,  134,  142,  145,  132,  133,  129,  146,
      127,  147,  126,  148,  106,  139,  146,  135,  147,  137,
      148,  140,  149,  138,  150,  153,  141,  154,  142,  149,
      105,  150,  153,  104,  154,  157,  178,  145,  158,  160,
      146,  160,  157,  148,  171,  158,  171,  171,  178,  176,
      147,  176,  176,  160,  178,  103,  101,  160,  154,  100,
       99,   60,   59,  150,   58,  149,  157,   57,  158,  153,
      161,  161,   55,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  165,  179,   52,   46,   26,   11,
       10,    5,    0,    0,    0,    0,    0,  179,    0,  165,
      165,    0,    0,  179,    0,  165,    0,    0,    0,    0,
        0,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      186,    0,  186,  186,  186,  186,  186,  186,  186,  187,
        0,  187,  187,  187,  187,  187,  187,  187,  188,  188,

        0,    0,  188,  188,  188,  189,    0,  189,  189,    0,
      189,  189,  189,  189,  190,    0,  190,  190,  190,  190,
      190,  190,  190,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  192,    0,  192,  192,  192,  192,  192,  192,
      192,  193,    0,  193,  193,  193,  193,  193,  193,  193,
      194,    0,  194,  194,  194,  194,  194,  194,  194,  195,
        0,    0,    0,    0,  195,  195,  196,    0,    0,    0,
        0,  196,  197,    0,    0,    0,    0,  197,  199,  199,
      199,  200,  200,  200,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 4 "lexer.l"
	#include<stdio.h>
	#include<string.h>
	
	struct ConstantTable{
		char constant_name[100];
		char constant_type[100];
		int exist;
	}CT[1000];
	
	struct SymbolTable{
		char symbol_name[100];
		char symbol_type[100];
		int exist;
	}ST[1000];
	
	unsigned long hash(unsigned char *str)
	{
		unsigned long hash = 5381;
		int c;

		while (c = *str++)
			hash = ((hash << 5) + hash) + c;

		return hash;
	}
	
	int search_ConstantTable(char* str){
		unsigned long temp_val = hash(str);
		int val = temp_val%1000;
		
		if(CT[val].exist == 0){
			return 0;
		}
		
		else if(strcmp(CT[val].constant_name, str) == 0)
		{
			return 1;
		}
		else
		{
			for(int i = val+1 ; i!=val ; i = (i+1)%1000)
			{
				if(strcmp(CT[i].constant_name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}

	
	int search_SymbolTable(char* str){
		unsigned long temp_val = hash(str);
		int val = temp_val%1000;
		
		if(ST[val].exist == 0){
			return 0;
		}
		
		else if(strcmp(ST[val].symbol_name, str) == 0)
		{
			return 1;
		}
		else
		{
			for(int i = val+1 ; i!=val ; i = (i+1)%1000)
			{
				if(strcmp(ST[i].symbol_name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}
	
	
	void insert_ConstantTable(char* name, char* type){
		int index = 0;
		 if(search_ConstantTable(name)){
			return;
		}
		else{
			unsigned long temp_val = hash(name);
			int val = temp_val%1000;
			if(CT[val].exist == 0){
				strcpy(CT[val].constant_name, name);
				strcpy(CT[val].constant_type, type);
				CT[val].exist = 1;
				return;
			}
			
			for(int i = val+1; i != val; i = (i+1)%1000){
				if(CT[i].exist == 0){
					index = i;
					break;
				}
			}
			strcpy(CT[index].constant_name, name);
			strcpy(CT[index].constant_type, type);
			CT[index].exist = 1;			
		}
	}
	
	void insert_SymbolTable(char* name, char* type){
		int index = 0;
		//printf("BBBB");
		 if(search_SymbolTable(name)){
			//printf("AAAAAA");
			return;
		}
		else{
			unsigned long temp_val = hash(name);
			int val = temp_val%1000;
			if(ST[val].exist == 0){
				strcpy(ST[val].symbol_name, name);
				strcpy(ST[val].symbol_type, type);
				ST[val].exist = 1;
				return;
			}
			
			for(int i = val+1; i != val; i = (i+1)%1000){
				if(ST[i].exist == 0){
					index = i;
					break;
				}
			}
			strcpy(ST[index].symbol_name, name);
			strcpy(ST[index].symbol_type, type);
			ST[index].exist = 1;			
		}
	}

	// Printing Tables
	void printConstantTable(){
		printf("CONSTANT TABLE:\n");
		for(int i = 0; i < 1000; ++i){
			if(CT[i].exist){
				printf("%s\t%s\n", CT[i].constant_name, CT[i].constant_type);
			}
		}
	}

	void printSymbolTable(){
		printf("SYMBOL TABLE:\n");
		for(int i = 0; i < 1000; ++i){
			if(ST[i].exist){
				printf("%s\t%s\n", ST[i].symbol_name, ST[i].symbol_type);
			}
		}
	}

	
/* Regular definitions */
#define MLCOMMENT 1

/* Pattern Matching Rules */
#line 771 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 175 "lexer.l"

	int nested_count = 0;
	int check_nested = 0;
#line 926 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 185 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 585 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 178 "lexer.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 179 "lexer.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 180 "lexer.l"
{ printf("Line No. %d PREPROCESSOR DIRECTIVE - %s\n", yylineno, yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 181 "lexer.l"
{ printf("Line No. %d PREPROCESSOR DIRECTIVE - %s\n", yylineno, yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 183 "lexer.l"
{ printf("Line No. %d SINGLE LINE COMMENT - %s\n", yylineno, yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 185 "lexer.l"
{ BEGIN MLCOMMENT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 186 "lexer.l"
{ ++nested_count; 
												check_nested = 1;
											 }	
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 189 "lexer.l"
{ if (nested_count) --nested_count;
											   else{ if(check_nested){
														printf("Line No. %d NESTED COMMENT\n", yylineno);
														check_nested = 0;
														BEGIN INITIAL;
														}
													 else{
														printf("Line No. %d MULTI LINE COMMENT\n", yylineno);
														BEGIN INITIAL;
													}
											    } 
											 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 201 "lexer.l"
; 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 202 "lexer.l"
;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 203 "lexer.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 204 "lexer.l"
;
	YY_BREAK
case YY_STATE_EOF(MLCOMMENT):
#line 205 "lexer.l"
{ printf("Line No. %d ERROR: MULTI LINE COMMENT NOT CLOSED\n", yylineno); return 0;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 208 "lexer.l"
{ 
                                                printf("Line No. %d STRING - %s\n", yylineno, yytext); 
                                                insert_ConstantTable(yytext, "String");
                                             }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 212 "lexer.l"
{ printf("Line No. %d ERROR: UNCLOSED STRING - %s\n", yylineno, yytext); return 0;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 214 "lexer.l"
{ 
                                                printf("Line No. %d CHARACTER - %s\n", yylineno, yytext); 
                                                insert_ConstantTable(yytext, "Character");
                                             }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 219 "lexer.l"
{ 
                                               printf("Line No. %d ERROR: NOT A CHARACTER - %s\n", yylineno, yytext); return 0; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 222 "lexer.l"
{ 
                                                printf("Line No. %d KEYWORD - %s\n", yylineno, yytext); 
                                             }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 226 "lexer.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 228 "lexer.l"
{
                                                printf("Line No. %d HEADER - %s\n", yylineno, yytext);                                                 
                                             }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 233 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 234 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 235 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 236 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 237 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 238 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 239 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 240 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 241 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 242 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 243 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 244 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 245 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 246 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 247 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 248 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 249 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 250 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 251 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 252 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 253 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 254 "lexer.l"
{ printf("Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 257 "lexer.l"
{	printf("Line No. %d FUNCTION - %s\n", yylineno, yytext);
												insert_SymbolTable(yytext, "Function");
											}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 262 "lexer.l"
{ printf("Line No. %d IDENTIFIER - %s\n", yylineno, yytext);
                                              insert_SymbolTable(yytext, "Identfier");
                                            }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 265 "lexer.l"
{ printf("Line No. %d INTEGER - %s\n", yylineno, yytext);
                                              insert_ConstantTable(yytext, "Integer");
                                            }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 268 "lexer.l"
{ printf("Line No. %d FLOATING POINT - %s\n", yylineno, yytext); 
                                              insert_ConstantTable(yytext, "Floating Point");
                                            }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 272 "lexer.l"
{ printf("Line No. %d LEFT BRACKET - %s\n", yylineno, yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 273 "lexer.l"
{ printf("Line No. %d RIGHT BRACKET - %s\n", yylineno, yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 274 "lexer.l"
{ printf("Line No. %d LEFT PARENTHESIS - %s\n", yylineno, yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 275 "lexer.l"
{ printf("Line No. %d RIGHT PARENTHESIS - %s\n", yylineno, yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 276 "lexer.l"
{ printf("Line No. %d LEFT BRACE - %s\n", yylineno, yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 277 "lexer.l"
{ printf("Line No. %d RIGHT BRACE - %s\n", yylineno, yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 278 "lexer.l"
{ printf("Line No. %d COMMA - %s\n", yylineno, yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 279 "lexer.l"
{ printf("Line No. %d SEMICOLON - %s\n", yylineno, yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 280 "lexer.l"
{ if(yytext[0] == '#')
													printf("Line No. %d PREPROCESSOR ERROR - %s\n", yylineno, yytext);
											   else
													printf("Line No. %d ERROR ILLEGAL CHARACTER - %s\n", yylineno, yytext);
											  return 0;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 286 "lexer.l"
ECHO;
	YY_BREAK
#line 1355 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 185 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 185 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 184);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 286 "lexer.l"


int yywrap(){
	return 1;
}

int main()
{
	extern FILE *yyin;
	yyin = fopen("test3.c","r");
	yylex();
	printf("-------------------------------------\n");
	printf("CONSTANT TABLE\n");
	printConstantTable();
	printf("-------------------------------------\n");
	printf("SYMBOL TABLE\n");
	printSymbolTable();
	return 0;
}
		
